### PR TITLE
Search interface

### PR DESCRIPTION
**Pull request by GopiGugan**
- Solution for #218 #219 #220 #223 #195 #161
- Added lineages to the data list for autocomplete
- Added an error message when:
  -  there are no search hits
  - the entered start date is after the end date
  - Date format is invalid

### CODE REVIEW

**Comment by ArtPoon** [comment]
Pulled this branch and tried to run it as localhost, caught this error:
```js
Uncaught ReferenceError: index_lineage is not defined
    at Object.<anonymous> (covizu.js:137)
    at fire (jquery.js:3496)
    at Object.fireWith [as resolveWith] (jquery.js:3626)
    at done (jquery.js:9786)
    at XMLHttpRequest.<anonymous> (jquery.js:10047)
```

**Comment by GopiGugan** [comment]
That's odd. ``index_lineage`` is defined in the ``search.js`` file:

https://github.com/PoonLab/covizu/blob/e8881e3cb936387482b4f84674a7bc20ac7dc47b/js/search.js#L693

Can you try clearing cached images and files and then run it again?

**Comment by ArtPoon** [comment]
Ok I had to do a hard refresh - thought I did last time, but it's working now!

**Comment by ArtPoon** [comment]
Okay search is much snappier and date limits seem to be working, thanks @GopiGugan and @RouxCil 
One issue is that if I enter `B.1.1.7` in the search text field and run the search, the page is locked for a long time.  I didn't wait for it to finish but Chrome was running on 100% CPU for a while.  On the other hand, if I use the browser Find function to search for `B.1.1.7` and then click on that cluster to render the bead plot, it only takes about 5 seconds.
The expected behaviour should be to jump to and highlight the cluster (rendering the beadplot and moving the rectangular box to the corresponding tip in the tree), *not* to select that cluster and all beads contained in that cluster.  Sorry :-/

**Comment by GopiGugan** [comment]
Sure, I can change that. So it should just highlight the cluster (select the corresponding cluster and reduce the opacity of all other clusters), generate the table for all beads, and not select any beads in the cluster, right?

**Comment by GopiGugan** [comment]
Removing the bead selection reduces the time a bit when searching ``B.1.1.7``

**Comment by ArtPoon** [comment]
Thanks for fixing that @GopiGugan, works much better now.  Recording another small bug - don't work on this on the weekend, I'm just recording it for future reference.

To reproduce:
1. Load page and enter "Portugal" into search field.
2. Click on any bead that was not selected by the search.  
3. Search buttons are disabled and search state is cleared, but search fields display previous search parameters.

Expected behaviour - if we are exiting search state then search fields should be reset as a visual cue to the user (in addition to all beads going opaque) about this change of state.

At some point we will have to address the time it takes to render the really large bead plots (e.g., B.1.1.7), at least with some visual indication to the user that it is being rendered (e.g., spinning beachball?).

**Review by ArtPoon — APPROVED** [review]

**Review by RouxCil — APPROVED** [review]

**Pull request merged**
