### PR TITLE
Deprecate countries.json and bug fix

### PR DESCRIPTION
**Pull request by ArtPoon**
* #420 
* #376

### CODE REVIEW

**Comment by GopiGugan** [comment]
Running the `dev` branch generates the following error:
```python
Traceback (most recent call last):
  File "batch.py", line 157, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "covizu/covizu/utils/batch_utils.py", line 246, in make_beadplots
    beaddict = beadplot.serialize_tree(ctree)
  File "covizu/covizu/beadplot.py", line 161, in serialize_tree
    while(not parents[id].labels):
KeyError: Clade(branch_length=0.0, confidence=1.0, name='')
```

**Comment by bonnielu** [comment]
Huh, I did not realize that unsampled nodes could act as roots—I just pushed a potential fix that should account for this! My test data set doesn't have an instance of this case so I haven't been able to explicitly test it, but it should hopefully solve the issue.

**Comment by ArtPoon** [comment]
Running into problems with how unsampled lineages get rendered - update issue with this, including screen capture of example please!

**Comment by bonnielu** [comment]
Current algorithm results in a clumping of the unsampled variants in the middle of the beadplot. Unsampled variants are currently ordered with their first date being the first date of their parent and their last date being the first date of the earliest child. Several of the unsampled lineages share the same parent in the larger beadplots, leading to this issue:

image

**Comment by GopiGugan** [comment]
* `temporarily disabled cron job`
* `python3 setup.py install --user`
* `module load openmpi/gnu`
* `nohup python3 batch.py --dry-run > pr-432.log &`

**Comment by GopiGugan** [comment]
Checking the following:
- [x] Search
    - [x] Search by accession number
    - [x] Search by lineage
    - [x] Search by country
    - [x] Search by country (with date filter)
- [x] Tree filtering
- [x] Download Time-scaled tree (nwk)
- [x] Download Time-scaled tree (csv)
- [x] Download Beadplot (svg)
- [x] Download Beadplot (nwk)
- [x] Beadplot cutoff slider
- [x] Expanding Beadplot
- [x] Translated pages
- [x] Changing the colour of the tree based on divergence, collection date, etc.
- [x] Left/Right arrow key to move between beads
- [x] Tooltips

**Pull request merged**
