### PR TITLE
0.4 release candidate 3

### PR DESCRIPTION
**Pull request by ArtPoon**
* hard limit of number of variants per lineage of 20K, to reduce computing time and avoid out-of-memory crashes
* restored scrollbar for beadplots to deal with massive lineages
* save beadplot as SVG
* merge search-interface branch
* beadplot loading visual feedback

### CODE REVIEW

**Comment by ArtPoon** [comment]
Running a test job on the cluster with `dev` branch right now (commit ee4e352)

**Review by GopiGugan — APPROVED** [review]
- Pulled the current ``dev`` branch and tested the front-end. Everything seems to be working fine. 
- Reviewed the changes from the commits.

**Comment by ArtPoon** [comment]
```
🏄 [1 day, 4:16:33.811121] All done!
```

**Comment by ArtPoon** [comment]
Found a bug, need help @GopiGugan @horaciobam.  
To repro:
* Select a relatively small beadplot.
* Export the SVG.
* Switch to a larger beadplot (more variants).
* New SVG is now truncated to vertical extent of previous beadplot.

Screen Shot 2021-03-03 at 10 02 47 PM

**Comment by ArtPoon** [comment]
Beadplot SVG on load, select small cluster:
Screen Shot 2021-03-03 at 10 08 53 PM

Export SVG:
Screen Shot 2021-03-03 at 10 09 19 PM

Switch to longer beadplot:
Screen Shot 2021-03-03 at 10 10 12 PM

**Comment by ArtPoon** [comment]
Can we wipe the style of the SVG when switching between beadplots?

**Comment by GopiGugan** [comment]
Nice catch. Yes, the latest commit removes the attributes once the SVG has been exported

**Pull request merged**
