### PR TITLE
Dev - Migrate to database

### PR DESCRIPTION
**Pull request by nav-mohan**
- Includes script for deleting/creating MongoDB user accounts.
- Includes script for updating the database 
- Includes documentation on how to install and configure MongoDB. 
- Scripts were written under the assumption that we would be running two instances of a database per server.

### CODE REVIEW

**Comment by GopiGugan** [comment]
@nav-mohan to fix paths for the front-end unit tests

@GopiGugan to test PR

**Comment by nav-mohan** [comment]
I think the frontend tests might be failing because the YML file for our Github Actions needs to be updated. 
The [error seems](https://github.com/PoonLab/covizu/actions/runs/5588253960/job/15134557342?pr=487#step:3:88) to suggest that the Github Action cannot find the `cypress.config.js` file because I moved it into the `./config/` folder. 
So we just need to [specify the path](https://github.com/cypress-io/github-action#config-file) to `cypress.config.js` explicity

**Comment by ArtPoon** [comment]
Please provide instructions for building a local database prior to merging this into `dev`, so that each of us can revise our build/test environments!

**Comment by GopiGugan** [comment]
Building the database with production data takes over 30 minutes. Looking to see if there are ways to optimize this

**Pull request merged**
