### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ArtPoon**
* #389 
* #419 
* #442 
* #436

### CODE REVIEW

**Comment by ArtPoon** [comment]
@bonnielu it looks like the fix for #442 may have broken the unit test for other language pages?

**Comment by GopiGugan** [comment]
There are no backend changes in this PR, but we're doing a complete run to make sure nothing breaks:
*  temporarily disabled the cron job
* checkout `dev` branch, pull changes
* `python3 setup.py install --user`
* `module load openmpi/gnu`
* `nohup python3 batch.py --dry-run > pr-449.log &`

**Comment by GopiGugan** [comment]
Checking the following:
- [ ] Search
    - [ ] Search by accession number
    - [ ] Search by lineage
    - [ ] Search by country
    - [ ] Search by country (with date filter)
- [ ] Tree filtering
- [ ] Download Time-scaled tree (nwk)
- [ ] Download Time-scaled tree (csv)
- [ ] Download Beadplot (svg)
- [ ] Download Beadplot (nwk)
- [ ] Beadplot cutoff slider
- [ ] Expanding Beadplot
- [ ] Translated pages
- [ ] Changing the colour of the tree based on divergence, collection date, etc.
- [ ] Left/Right arrow key to move between beads
- [ ] Tooltips
- [ ] Countries/Samples/Mutations tabs are populating the correct information

**Comment by GopiGugan** [comment]
I've been having trouble getting the `--watch` option to work with `pm2 reload` to reload the node servers when a change to the data files is detected. It works with `pm2 restart` but this would restart both instances of the node server. As a workaround, to ensure zero downtime, we can just schedule a cron job to reload the node servers (one after the other), at midnight every day.

**Pull request merged**
