### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by ArtPoon**

### CODE REVIEW

**Comment by ArtPoon** [comment]
@MomomomoLiu can you please review these additional lines?
https://github.com/PoonLab/covizu/blob/d168753d31dc78bc7695ef496355870dddeed3dc/index-zh.html#L43-L50
https://github.com/PoonLab/covizu/blob/d168753d31dc78bc7695ef496355870dddeed3dc/index-zh.html#L59-L79

**Comment by MomomomoLiu** [comment]
line 62 vedge_support: "支持", 
line 65 hedge_unique_dates: "独特的收集日期", 
it is a bit weird :(
 I would like to double-check these lines meaning with you before merging

**Comment by ArtPoon** [comment]
> line 62 vedge_support: "支持",
> line 65 hedge_unique_dates: "独特的收集日期",
> it is a bit weird :(
> I would like to double-check these lines meaning with you before merging

Yes those are fresh out of Google Translate, so I'm not surprised they sound weird :-)
Please refer to `index.html` for original English terms.

**Comment by ArtPoon** [comment]
Need to add this to `i18n_text` JSON:
https://github.com/PoonLab/covizu/blob/e678f0ca1ea486a9381af226b39781d8c4ba2e5f/js/search.js#L46-L48

**Comment by ArtPoon** [comment]
@RouxCil suggests moving the template into the JSON:
```
function update_search_stats(stats) { 
   $('#search_stats').text(i18n_text.placeholder); 
 } 
```

in `index.html`:
```js
i18n_text = {
  placeholder: `${stats.current_point+1} foo ${stats.total_points} bar`; 
}
```

**Comment by ArtPoon** [comment]
@GopiGugan - It would be better to zero the counts in the template string instead of having a `zero_points` placeholder

**Comment by ArtPoon** [comment]
Looks good, thanks @GopiGugan and @MomomomoLiu

**Pull request merged**
