### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ArtPoon**

### CODE REVIEW

**Comment by GopiGugan** [comment]
- temporarily disabled cron job
- checked out `dev` branch
- `python3 setup.py install --user`
- `module load openmpi/gnu`
- `nohup python3 batch.py --dry-run > pr-382.log &`

**Comment by GopiGugan** [comment]
Run was successful:

```console
[covizu@BEVi covizu]$ tail pr-382.log 
🏄 [20:53:11.556723] start AY.99.2, 16532 entries
🏄 [21:03:32.205616] start P.1.14, 13565 entries
🏄 [21:12:48.721808] start D.2, 9251 entries
🏄 [21:14:27.290780] start B.1.1.214, 18089 entries
🏄 [21:23:55.702977] start B.1.1.284, 9159 entries
🏄 [21:27:50.960942] start B.1.177.21, 6777 entries
🏄 [21:29:58.339209] start B.1.177.12, 6025 entries
🏄 [21:31:13.118376] start AY.69, 10832 entries
🏄 [21:40:15.383189] Parsing output files
🏄 [23:48:25.713337] All done!
```

**Comment by ArtPoon** [comment]
Great!  just need to check the three front-ends and we'll be able to merge
thanks @GopiGugan

**Comment by ArtPoon** [comment]
need to take note that our run time is now nearly two days - we will probably have to revise our updating interval to every three days.

**Comment by GopiGugan** [comment]
> Great! just need to check the three front-ends and we'll be able to merge thanks @GopiGugan

* Reviewed the `epicov` branch. Changes to the `dbstats.json` file does not break the front-end. 
* `dev` branch front-end runs as expected without issues.

**Pull request merged**
