### PR TITLE
Improve page load times

### PR DESCRIPTION
**Pull request by GopiGugan**
Changes related to:
* #373 - Improve page load times
* #387 - Memory consumption of `by_lineage`
* #402

### CODE REVIEW

**Comment by GopiGugan** [comment]
Tests from #387 shows that `clusters.json` was the same as the `dev` branch.

**Comment by GopiGugan** [comment]
Screen Shot 2022-05-16 at 11 27 22 PM

Need to fix the scale

**Comment by GopiGugan** [comment]
> Issues to fix:
> 
> * Fix the scale:

This issue was related to a change I made. Pushing a fix.

> * Missing edges when first clicking on a cluster:

This issue does not seem to be related to this specific branch. To reproduce:
* Pull the master branch and use the latest data files or go to https://filogeneti.ca/covizu/
* Click on the `B.1.588` cluster
* Slider value displays as 2.0 but it is actually a value less than 2.0
* Select the left or right arrow button

**Comment by ArtPoon** [comment]
Congrats @GopiGugan - great work!

**Pull request merged**
