### PR TITLE
Resize beadplot

### LINKED ISSUE #132: Resize horizontal dimension of window should resize beadplot
See #49 
Should be a matter of setting a parameter in CSS to determine how the beadplot drawing region responds to resizing the window..

### PR DESCRIPTION
**Pull request by gopigugan**
- Fixes #132 
- Used Flexbox for website layout
- In ``beadplot.js``, instead of a fixed width of 700, the width is set based on the size of div holding the beadplot
- In the function ``beadplot()``, added ``redraw()`` to draw the beadplot again when the user increases the size of the window

### CODE REVIEW

**Comment by ArtPoon** [comment]
SVG is rescaling up, which is great, but it is not going back down when user reduces client window width.
Please set minimum width for beadplot to 500px for now.

**Comment by ArtPoon** [comment]
Hi @gopigugan this looks good but we have some new changes in the dev branch, can you please handle the merge?

**Comment by gopigugan** [comment]
Sure, I'll resolve the conflicts and merge it to the dev branch

**Comment by ArtPoon** [comment]
Thanks let me know if you need me to explain any of the recent commits in dev branch

**Pull request closed without merging**
