### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ArtPoon**

### CODE REVIEW

**Comment by ArtPoon** [comment]
Run test of `dev` branch on cluster following resolution of #263

**Comment by ArtPoon** [comment]
Thanks for implementing that @GopiGugan - I just tried it out and the right arrow button is blocked by the slider:
Screen Shot 2021-05-18 at 3 43 30 PM

**Comment by GopiGugan** [comment]
Yes I ran into that problem as well. To overcome this, I can add extra space around the slider:

Slider
Slider Max Value

Would that be okay?

**Comment by ArtPoon** [comment]
Erg, that doesn't look great either.  I think the left button is not affected by this overlap because we are limiting the slider to a minimum of 0.5.  Can we add 0.5 to the maximum range of the slider instead of moving the buttons?

**Comment by GopiGugan** [comment]
Sure I can try that

**Comment by GopiGugan** [comment]
>Can we add 0.5 to the maximum range of the slider instead of moving the buttons?

The problem with this approach is that there isn't one value that works for all cases. For example if the max_dist is less than 10, then only a small value needs to be added. If the max_dist is greater than 10, then a larger value needs to the maximum value. 

I tried another approach (moving the right arrow key button). Would that work?

**Comment by ArtPoon** [comment]
Ha the moving button is hilarious, let's keep it :-D

**Comment by ArtPoon** [comment]
Pipeline is currently in progress (about 22 hours in).  @artpoon to freeze cron job tomorrow morning and run `dev` branch test.

**Comment by ArtPoon** [comment]
Using procedure in previous PR:
https://github.com/PoonLab/covizu/pull/272#issuecomment-814508612

**Comment by ArtPoon** [comment]
Strange negative branch lengths in `timetree.nwk` - turns out I forgot to activate selection of earliest samples in the pipeline.
Screen Shot 2021-05-21 at 9 25 54 AM
Modified settings and re-running with `treetime.py` command-line interface on `by_lineages.json`.

**Comment by ArtPoon** [comment]
Fixed, but I realized that we have to roll in some changes into the `epicov` branch, or else that front end won't be able to display these new trees properly.  @GopiGugan can you please help with that?  I can send you the current data files.

**Comment by ArtPoon** [comment]
It has to be done with a little caution because `epicov` has some features specific to that front-end.

**Comment by ArtPoon** [comment]
So I would focus on the differences that would otherwise cause `epicov` to fail to render the tree properly.

**Comment by GopiGugan** [comment]
Some of the changes have been merged into the `epicov` branch

**Comment by ArtPoon** [comment]
Thanks!  Have you tested it locally?

**Comment by GopiGugan** [comment]
Yes I have. Didn't run into any issues!

**Comment by ArtPoon** [comment]
Ok thanks, I'll spin up a `dev` run on the cluster tonight

**Pull request merged**
