### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ArtPoon**

### CODE REVIEW

**Comment by ArtPoon** [comment]
* need to credit Pokay authors on front page
* test fixes for #349, #342, #347

**Comment by ArtPoon** [comment]
@bonnielu to check front end unit tests on `dev`
@ArtPoon to do some general testing

**Comment by bonnielu** [comment]
All of the tests passed except for one! I think that this is associated with a previous pull request, but for tips with 1 sample and  `Displayed: 1` in the tooltip, the number of sampled variants is listed as `undefined`.

**Comment by ArtPoon** [comment]
Tested on my local machine, I think this is good to go

**Pull request merged**
